# Generated by Django 6.0 on 2026-02-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "блоговая запись",
                "verbose_name_plural": "блоговые записи",
            },
        ),
    ]
