# Generated by Django 6.0 on 2026-01-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description_category",
            field=models.TextField(verbose_name="Описание категории"),
        ),
    ]
